name: pypgo-conda-mkl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - cmake>=3.29
  - ninja
  - pkg-config
  - gmp
  - mpfr
  - imath
  - libblas=*=*mkl
  - liblapack=*=*mkl
  - zlib
  - eigen>=3.4,<4
  - libboost-devel
  - tbb-devel
  - gmsh
  - openvdb
  - mkl-devel
  - numpy
  - pip
  - setuptools
  - wheel
