#include "volumetricMeshExport.h"

#include "tetMesh.h"
#include "tetMeshGeo.h"

#include <cstdio>

namespace pgo::VolumetricMeshes {
namespace exporting {
namespace detail {

Geometry geometry_impl(const VolumetricMesh& mesh) {
    Geometry result;
    const auto vertices = mesh.getVertices();
    const auto elements = mesh.getElements();
    result.vertices = std::vector<Vec3d>(vertices.begin(), vertices.end());
    result.elements = std::vector<int>(elements.begin(), elements.end());
    result.numElementVertices = mesh.getNumElementVertices();
    return result;
}

void to_ele_impl(const VolumetricMesh& mesh, const std::filesystem::path& baseFilename, bool includeRegions) {
    const std::filesystem::path elePath = baseFilename.string() + ".ele";
    const std::filesystem::path nodePath = baseFilename.string() + ".node";

    FILE* eleOut = fopen(elePath.string().c_str(), "w");
    if (!eleOut) {
        printf("Error: could not write to %s.\n", elePath.string().c_str());
        throw 1;
    }
    FILE* nodeOut = fopen(nodePath.string().c_str(), "w");
    if (!nodeOut) {
        fclose(eleOut);
        printf("Error: could not write to %s.\n", nodePath.string().c_str());
        throw 1;
    }

    std::vector<int> elementRegion;
    if (includeRegions) {
        elementRegion.resize(static_cast<size_t>(mesh.getNumElements()));
        for (int el = 0; el < mesh.getNumElements(); el++) {
            int found = 0;
            for (int region = 0; region < mesh.getNumRegions(); region++) {
                int elementSet = mesh.getRegion(region).getSetIndex();
                if (mesh.getSet(elementSet).isMember(el)) {
                    if (found != 0)
                        printf("Warning: element %d (1-indexed) is in more than one region.\n", el + 1);
                    else
                        found = region + 1;
                }
            }
            if (found == 0)
                printf("Warning: element %d (1-indexed) is not in any of the regions.\n", el + 1);
            elementRegion[static_cast<size_t>(el)] = found;
        }
    }

    fprintf(eleOut, "%d %d %d\n", mesh.getNumElements(), mesh.getNumElementVertices(), includeRegions ? 1 : 0);

    for (int el = 0; el < mesh.getNumElements(); el++) {
        fprintf(eleOut, "%d ", el + 1);
        for (int j = 0; j < mesh.getNumElementVertices(); j++) {
            fprintf(eleOut, "%d", mesh.getVertexIndex(el, j) + 1);
            if (j != mesh.getNumElementVertices() - 1)
                fprintf(eleOut, " ");
        }
        if (includeRegions)
            fprintf(eleOut, " %d", elementRegion[static_cast<size_t>(el)]);
        fprintf(eleOut, "\n");
    }

    fprintf(eleOut, "# generated by the volumetricMesh export namespace\n");

    fprintf(nodeOut, "%d 3 0 0\n", mesh.getNumVertices());
    for (int vi = 0; vi < mesh.getNumVertices(); ++vi) {
        const Vec3d& v = mesh.getVertex(vi);
        fprintf(nodeOut, "%d %.15G %.15G %.15G\n", vi + 1, v[0], v[1], v[2]);
    }
    fprintf(nodeOut, "# generated by the volumetricMesh export namespace\n");

    fclose(eleOut);
    fclose(nodeOut);
}

}  // namespace detail

Geometry geometry(const VolumetricMesh& mesh) {
    return detail::geometry_impl(mesh);
}

void geometry(const VolumetricMesh& mesh, std::vector<Vec3d>& verticesOut, std::vector<int>& elementsOut) {
    const auto vertices = mesh.getVertices();
    const auto elements = mesh.getElements();
    verticesOut.assign(vertices.begin(), vertices.end());
    elementsOut.assign(elements.begin(), elements.end());
}

void vertices(const VolumetricMesh& mesh, std::vector<Vec3d>& verticesOut) {
    const auto vertices = mesh.getVertices();
    verticesOut.assign(vertices.begin(), vertices.end());
}

int to_ele(const VolumetricMesh& mesh, const std::filesystem::path& baseFilename, bool includeRegions) {
    try {
        detail::to_ele_impl(mesh, baseFilename, includeRegions);
        return 0;
    } catch (...) {
        return 1;
    }
}

void tet_geometry(const TetMesh& mesh, std::vector<Vec3d>& verticesOut, std::vector<Vec4i>& tets) {
    const auto vertices = mesh.getVertices();
    verticesOut.assign(vertices.begin(), vertices.end());
    tets.resize(static_cast<size_t>(mesh.getNumElements()));
    for (int i = 0; i < mesh.getNumElements(); ++i) {
        const auto ii = mesh.getVertexIndices(i);
        tets[static_cast<size_t>(i)] = Vec4i(ii[0], ii[1], ii[2], ii[3]);
    }
}

void tet_geometry(const TetMesh& mesh, Mesh::TetMeshGeo& geo) {
    tet_geometry(mesh, geo.positions(), geo.tets());
}

}  // namespace exporting
}  // namespace pgo::VolumetricMeshes
