#include "io/mesh_save.h"

#include "io/mesh_ascii_writer.h"
#include "io/mesh_binary_writer.h"
#include "io/mesh_format_detector.h"

#include <cstdio>

namespace pgo::VolumetricMeshes::io {

namespace {

void save_to_node_ele_impl(const VolumetricMesh& mesh, const std::filesystem::path& baseFilename,
                           bool includeRegions) {
    const std::filesystem::path elePath  = baseFilename.string() + ".ele";
    const std::filesystem::path nodePath = baseFilename.string() + ".node";

    FILE* eleOut = fopen(elePath.string().c_str(), "w");
    if (!eleOut) {
        printf("Error: could not write to %s.\n", elePath.string().c_str());
        throw 1;
    }
    FILE* nodeOut = fopen(nodePath.string().c_str(), "w");
    if (!nodeOut) {
        fclose(eleOut);
        printf("Error: could not write to %s.\n", nodePath.string().c_str());
        throw 1;
    }

    std::vector<int> elementRegion;
    if (includeRegions) {
        elementRegion.resize(static_cast<size_t>(mesh.getNumElements()));
        for (int el = 0; el < mesh.getNumElements(); el++) {
            int found = 0;
            for (int region = 0; region < mesh.getNumRegions(); region++) {
                const int elementSet = mesh.getRegion(region).getSetIndex();
                if (mesh.getSet(elementSet).isMember(el)) {
                    if (found != 0)
                        printf("Warning: element %d (1-indexed) is in more than one region.\n", el + 1);
                    else
                        found = region + 1;
                }
            }
            if (found == 0)
                printf("Warning: element %d (1-indexed) is not in any of the regions.\n", el + 1);
            elementRegion[static_cast<size_t>(el)] = found;
        }
    }

    fprintf(eleOut, "%d %d %d\n", mesh.getNumElements(), mesh.getNumElementVertices(), includeRegions ? 1 : 0);

    for (int el = 0; el < mesh.getNumElements(); el++) {
        fprintf(eleOut, "%d ", el + 1);
        for (int j = 0; j < mesh.getNumElementVertices(); j++) {
            fprintf(eleOut, "%d", mesh.getVertexIndex(el, j) + 1);
            if (j != mesh.getNumElementVertices() - 1)
                fprintf(eleOut, " ");
        }
        if (includeRegions)
            fprintf(eleOut, " %d", elementRegion[static_cast<size_t>(el)]);
        fprintf(eleOut, "\n");
    }

    fprintf(eleOut, "# generated by the volumetricMesh io namespace\n");

    fprintf(nodeOut, "%d 3 0 0\n", mesh.getNumVertices());
    for (int vi = 0; vi < mesh.getNumVertices(); ++vi) {
        const Vec3d& v = mesh.getVertex(vi);
        fprintf(nodeOut, "%d %.15G %.15G %.15G\n", vi + 1, v[0], v[1], v[2]);
    }
    fprintf(nodeOut, "# generated by the volumetricMesh io namespace\n");

    fclose(eleOut);
    fclose(nodeOut);
}

}  // namespace

int save(const VolumetricMesh& mesh, const std::filesystem::path& filename) {
    const FileFormatType file_type = detect_file_format(filename);
    if (file_type == FileFormatType::Binary)
        return save_to_binary(mesh, filename);
    return save_to_ascii(mesh, filename);
}

int save_to_ascii(const VolumetricMesh& mesh, const std::filesystem::path& filename) {
    try {
        detail::write_ascii_mesh(mesh, filename);
        return 0;
    } catch (...) {
        return 1;
    }
}

int save_to_binary(const VolumetricMesh& mesh, const std::filesystem::path& filename, unsigned int* bytesWritten) {
    try {
        detail::write_binary_mesh(mesh, filename, bytesWritten);
        return 0;
    } catch (...) {
        return 1;
    }
}

int save_to_node_ele(const VolumetricMesh& mesh, const std::filesystem::path& baseFilename, bool includeRegions) {
    try {
        save_to_node_ele_impl(mesh, baseFilename, includeRegions);
        return 0;
    } catch (...) {
        return 1;
    }
}

}  // namespace pgo::VolumetricMeshes::io
